name: RAG Chatbot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort
        pip install -r requirements.txt
    
    - name: Run code formatting checks
      run: |
        # Check if code is formatted with black
        black --check --diff .
        
        # Check import sorting
        isort --check-only --diff .
        
        # Run linting with ruff
        ruff check .
      continue-on-error: true
    
    - name: Run tests (if any)
      run: |
        echo "No tests defined yet - skipping test phase"
        # pytest tests/ --cov=. --cov-report=xml
      continue-on-error: true

  build-and-test:
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build backend Docker image
      run: |
        docker build -f backend/Dockerfile -t rag-chatbot-backend .
    
    - name: Build frontend Docker image
      run: |
        docker build -f frontend/Dockerfile -t rag-chatbot-frontend .
    
    - name: Test Docker Compose
      run: |
        echo "Testing docker-compose configuration"
        docker-compose config
    
    - name: Run integration test
      run: |
        echo "Integration tests would go here"
        # docker-compose up -d
        # curl -f http://localhost:8000/health || exit 1
        # docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: [code-quality, build-and-test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2 (Simulation)
      run: |
        echo "🚀 Deployment simulation"
        echo "In a real setup, this would:"
        echo "- SSH into EC2 instance"
        echo "- Pull latest code"
        echo "- Rebuild containers"
        echo "- Restart services"
        echo "- Run health checks"
        echo ""
        echo "Commands that would run on EC2:"
        echo "git pull origin main"
        echo "docker-compose down"
        echo "docker-compose up --build -d"
        echo "docker-compose ps"
